production:
    riurl: https://repository.cul.columbia.edu:8443/fedora
development:
    riurl: https://repository2.cul.columbia.edu:8443/fedora
    riquery: "select $member from <#ri> where walk ($obj <cul:memberOf> <fedora:%s> and $member <cul:memberOf> $obj) and $member <rdf:type> <cul:Aggregator>"
test:
    riurl: https://repository2.cul.columbia.edu:8443/fedora
    riquery: "select $member from <#ri> where walk ($obj <cul:memberOf> <fedora:%s> and $member <cul:memberOf> $obj) and $member <rdf:type> <cul:Aggregator>"
