production:
    url: http://testcat.cul.columbia.edu:8983/solr/blacklight
development:
    url: http://testcat.cul.columbia.edu:8983/solr/blacklight
test:
    url: http://testcat.cul.columbia.edu:8983/solr/blacklight
