production:
    url: http://testcat.cul.columbia.edu:8983/solr-1.4/blacklight
development:
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/blacklight
test:
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/blacklight
